### ISSUE TITLE
신고서 등 그림 파일의 글씨가 너무 작음

### ISSUE THREAD

**Issue by taiji202** [jinbonetwork/the-art-of-protest-android#29]
"신고서 같은 그림 파일의 글씨가 너무 작아서 잘 안보이네요. 터치해서 확대되면 좋을 텐데요" 라는 의견이 있네요 어떻게 하는 게 좋을지 같이 얘기해 봐용

**Comment by mmx900** [comment]
또다른 예시 : https://github.com/mhartington/PinchToZoom/blob/master/www/templates/modal.html

**Comment by mmx900** [comment]
figure로 설정된 이미지에 한해 이미지 클릭시 이미지 뷰어 창이 표시되도록 수정함.
