### ISSUE TITLE
앱 실행 후 업데이트 중 메시지 없이 종료됨

### ISSUE THREAD

**Issue by taiji202** [jinbonetwork/the-art-of-protest-android#46]
LG optimus LTE2(d1lkt)  앱 버전  32(0.0.3)  운영체제  Android 4.1

**Comment by taiji202** [comment]
안드로이드 버전 4.1.2 - 휴대폰 모델번호 LG-F160L

**Comment by taiji202** [comment]
안드로이드 4.4.2 G3

**Comment by mmx900** [comment]
일부 기종에서 ContentSync 실행 중 크래시되는 문제이나, 구체적인 오류가 뿌려지지 않아 더 확인이 필요합니다. 일단은 캐시 기능을 우회해야 할 것 같네요.

**Comment by taiji202** [comment]
더 이상 발생하지 않습니다 :dancer:

**Comment by taiji202** [comment]
더 이상 발생하지 않습니다 :dancer:
