### ISSUE TITLE
텍스트 선택하기

### ISSUE THREAD

**Issue by taiji202** [jinbonetwork/the-art-of-protest-android#49]
본문을 복사할 수 있게★

**Comment by mmx900** [comment]
참고 소스 : https://forum.ionicframework.com/t/is-making-a-div-text-selectable-an-impossible-task-with-ionic/34299/3

**Comment by mmx900** [comment]
공지와 본문에서는 활성화하였으나 첫 화면의 링크의 경우 안드로이드 브라우저의 기본 동작에서처럼 텍스트 선택이 활성화되지 않습니다.
