### ISSUE TITLE
최근 업데이트 내용 불러오지 못함

### ISSUE THREAD

**Issue by taiji202** [jinbonetwork/the-art-of-protest-android#50]
오늘자로 업데이트해봤는데 최종 업데이트 날짜도 10월 1일이고 본문도 업데이트가 안 돼요.

**Comment by mmx900** [comment]
@taiji202 @hwangkm 새 버전 API(version.php)로 조회결과 home/content 각각 9월 4일/6일로 나오는데요. 이슈 올려주신 날이 10월 6일이니까 서버측에 문제가 있어 보이는데, 확인 부탁드립니다.

**Comment by mmx900** [comment]
더이상 발생하지 않으므로 닫습니다.
